/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import piagendamentos.Agendamento;
import piagendamentos.Cliente;
import piagendamentos.DaoAgendamento;
import piagendamentos.DaoClientes;
import piagendamentos.DaoFuncionario;
import piagendamentos.Funcionario;
import piagendamentos.util.FormatacaoData;
import piagendamentos.util.Horarios;

/**
 *
 * @author Elder
 */
public class FormPesquisaAgendamento extends javax.swing.JDialog {

    /**
     * Creates new form FormNovoCliente
     */
    public FormPesquisaAgendamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoRakusPeqNCli = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbo_pesquisaAgendamentoUnidade = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbo_pesquisaAgendamentoFuncionario = new javax.swing.JComboBox();
        btn_pesquisaAgendamentoFiltrar = new javax.swing.JButton();
        btn_pesquisaAgendamentoPesquisar = new javax.swing.JButton();
        txt_pesquisaAgendamentoCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_pesquisaAgendamentoCpf = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pesquisaAgendamento = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_pesquisaAgendamentoPesquisarAlterar = new javax.swing.JButton();
        txt_pesquisaAgendamentoId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_pesquisaAgendamentoFuncionarioAlterar = new javax.swing.JTextField();
        txt_pesquisaAgendamentoServicoAlterar = new javax.swing.JTextField();
        txt_pesquisaAgendamentoData = new javax.swing.JTextField();
        txt_pesquisaAgendamentoHorario = new javax.swing.JLabel();
        cbo_pesquisaAgendamentoAlterarHorario = new javax.swing.JComboBox();
        txt_pesquisaAgendamentoHorarioInicio = new javax.swing.JTextField();
        txt_pesquisaAgendamentoHorarioFim = new javax.swing.JTextField();
        txt_pesquisaAgendamentoSituacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_pesquisaAgendamentoSalvar = new javax.swing.JButton();
        cbo_pesquisaAgendamentoAlterarSituacao = new javax.swing.JComboBox();
        btn_pesquisaAgendamentoAlteraHora = new javax.swing.JCheckBox();
        btn_pesquisaAgendamentoAlteraSituacao = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rankuspelus - Pesquisa de Agendamento");
        setResizable(false);

        logoRakusPeqNCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoRankupeluspequeno.gif"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa de Agendamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 16))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("CPF Cliente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Unidade");

        cbo_pesquisaAgendamentoUnidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Interlagos", "Brooklin", "Faria Lima" }));
        cbo_pesquisaAgendamentoUnidade.setEnabled(false);
        cbo_pesquisaAgendamentoUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_pesquisaAgendamentoUnidadeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Funcionário");

        cbo_pesquisaAgendamentoFuncionario.setEnabled(false);

        btn_pesquisaAgendamentoFiltrar.setText("Filtrar");
        btn_pesquisaAgendamentoFiltrar.setEnabled(false);
        btn_pesquisaAgendamentoFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisaAgendamentoFiltrarActionPerformed(evt);
            }
        });

        btn_pesquisaAgendamentoPesquisar.setText("Pesquisar");
        btn_pesquisaAgendamentoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisaAgendamentoPesquisarActionPerformed(evt);
            }
        });

        txt_pesquisaAgendamentoCliente.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Cliente");

        try {
            txt_pesquisaAgendamentoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbo_pesquisaAgendamentoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbo_pesquisaAgendamentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_pesquisaAgendamentoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_pesquisaAgendamentoPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txt_pesquisaAgendamentoCliente))))
                .addGap(18, 18, 18)
                .addComponent(btn_pesquisaAgendamentoFiltrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_pesquisaAgendamentoPesquisar)
                    .addComponent(txt_pesquisaAgendamentoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_pesquisaAgendamentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbo_pesquisaAgendamentoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbo_pesquisaAgendamentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_pesquisaAgendamentoFiltrar)
                        .addGap(24, 24, 24))))
        );

        tbl_pesquisaAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Agendamento", "Funcionário", "Serviço", "Data", "Horário Início", "Horário Fim", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_pesquisaAgendamento.setFillsViewportHeight(true);
        tbl_pesquisaAgendamento.setFocusable(false);
        tbl_pesquisaAgendamento.setInheritsPopupMenu(true);
        tbl_pesquisaAgendamento.setRequestFocusEnabled(false);
        tbl_pesquisaAgendamento.setRowSelectionAllowed(false);
        tbl_pesquisaAgendamento.setUpdateSelectionOnSort(false);
        tbl_pesquisaAgendamento.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(tbl_pesquisaAgendamento);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 16))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Funcionário:");

        btn_pesquisaAgendamentoPesquisarAlterar.setText("Pesquisar");
        btn_pesquisaAgendamentoPesquisarAlterar.setEnabled(false);
        btn_pesquisaAgendamentoPesquisarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisaAgendamentoPesquisarAlterarActionPerformed(evt);
            }
        });

        txt_pesquisaAgendamentoId.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Código Agendamento:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Serviço:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Data:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Horário Início:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Horário Fim:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Situação:");

        txt_pesquisaAgendamentoFuncionarioAlterar.setEditable(false);

        txt_pesquisaAgendamentoServicoAlterar.setEditable(false);

        txt_pesquisaAgendamentoData.setEditable(false);

        txt_pesquisaAgendamentoHorario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_pesquisaAgendamentoHorario.setForeground(new java.awt.Color(153, 0, 0));
        txt_pesquisaAgendamentoHorario.setText("Alterar Horário:");

        cbo_pesquisaAgendamentoAlterarHorario.setEnabled(false);

        txt_pesquisaAgendamentoHorarioInicio.setEditable(false);

        txt_pesquisaAgendamentoHorarioFim.setEditable(false);

        txt_pesquisaAgendamentoSituacao.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Alterar Situação:");

        btn_pesquisaAgendamentoSalvar.setText("Salvar Alterações");
        btn_pesquisaAgendamentoSalvar.setEnabled(false);
        btn_pesquisaAgendamentoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisaAgendamentoSalvarActionPerformed(evt);
            }
        });

        cbo_pesquisaAgendamentoAlterarSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agendado", "Cancelado", "Em atendimento", "Atendido", "Fila de espera" }));
        cbo_pesquisaAgendamentoAlterarSituacao.setEnabled(false);

        btn_pesquisaAgendamentoAlteraHora.setEnabled(false);
        btn_pesquisaAgendamentoAlteraHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisaAgendamentoAlteraHoraActionPerformed(evt);
            }
        });

        btn_pesquisaAgendamentoAlteraSituacao.setEnabled(false);
        btn_pesquisaAgendamentoAlteraSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisaAgendamentoAlteraSituacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_pesquisaAgendamentoId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_pesquisaAgendamentoPesquisarAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_pesquisaAgendamentoSalvar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(txt_pesquisaAgendamentoData, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(146, 146, 146))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_pesquisaAgendamentoServicoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pesquisaAgendamentoFuncionarioAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pesquisaAgendamentoHorarioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pesquisaAgendamentoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_pesquisaAgendamentoHorarioFim, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_pesquisaAgendamentoHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_pesquisaAgendamentoAlteraHora))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_pesquisaAgendamentoAlteraSituacao)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_pesquisaAgendamentoAlterarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_pesquisaAgendamentoAlterarSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btn_pesquisaAgendamentoPesquisarAlterar)
                    .addComponent(txt_pesquisaAgendamentoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesquisaAgendamentoSalvar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_pesquisaAgendamentoFuncionarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_pesquisaAgendamentoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(21, 21, 21))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(txt_pesquisaAgendamentoHorarioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel12)
                                                    .addComponent(txt_pesquisaAgendamentoHorarioFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_pesquisaAgendamentoServicoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(cbo_pesquisaAgendamentoAlterarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txt_pesquisaAgendamentoHorario)
                                                    .addComponent(btn_pesquisaAgendamentoAlteraHora))
                                                .addGap(11, 11, 11)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbo_pesquisaAgendamentoAlterarSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_pesquisaAgendamentoAlteraSituacao))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_pesquisaAgendamentoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(24, 24, 24))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoRakusPeqNCli))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(logoRakusPeqNCli))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisaAgendamentoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisaAgendamentoPesquisarActionPerformed

        
        
        
        //Instanciando a classe de DaoCLientes, utilizada para pesquisas, alterações e inclusões no banco.

        DaoClientes daoClientes = new DaoClientes();
        
        String cpf = txt_pesquisaAgendamentoCpf.getText().replaceAll("[./-]", "");
        
        
        //Passa para o método "verificaExistencia" da classe DaoClientes, o cpf informado no textbox.
        //Se o método "verificaExistencia"retornar true, significa que o cpf foi encontrado no banco de dados

        if(daoClientes.verificaExistencia(cpf)){

            //Instanciando um cliente utilizando o método pesquisaCliente, passando como parêmatro o cpf
            //resgatado na textbox e recebendo como retorno um object Cliente.

            Cliente cliente = daoClientes.pesquisaCliente(cpf);
            
            //Setando o texto da textBox com o nome do cliente retornado no método "pesquisaCliente".

            txt_pesquisaAgendamentoCliente.setText(cliente.getNome());

            //Abrindo a visibilidade dos objetos de pesquisa.
            
            cbo_pesquisaAgendamentoUnidade.setEnabled(true);
            cbo_pesquisaAgendamentoFuncionario.setEnabled(true);
            btn_pesquisaAgendamentoFiltrar.setEnabled(true);
            
            DaoAgendamento daoAgend = new DaoAgendamento();
            
            DaoFuncionario daoFunc = new DaoFuncionario();
            
            ArrayList<Agendamento> lista = new ArrayList<>();
            
            lista = daoAgend.agendamentoPorCliente(cliente);
            
            DefaultTableModel model = (DefaultTableModel) tbl_pesquisaAgendamento.getModel();
            
            model.setNumRows(0);
            
            if(lista != null){
        
            for(Agendamento a : lista){
            
                Funcionario f = new Funcionario();
                
                f = daoFunc.pesquisaFuncionarioId(a.getIdFuncionario());
                
                Cliente c = daoClientes.pesquisaClienteId(a.getIdCliente());
            
                String nomeServico = daoFunc.pesquisaNomeServicoPorIdServico(a.getIdServico());
                                
                Date data = FormatacaoData.convertToDate(a.getDataAgendamento());
                
                model.addRow(new Object[] {a.getIdAgendamento(), 
                f.getNome(), nomeServico, FormatacaoData.convertToStringExibicao(data), a.getHoraInicio(), 
                a.getHoraFim(), a.getStatus()});
            
                }
            
            }

            

        }
        else{

            //Se o if retornar negativo, significa que não foi encontrado um cliente com o cpf informado.

            //Exibe uma caixa de dialogo solicitando confirmação ou não.
            //Se o usuário clicar em "Sim" retorna 0 pra variavel reply, se informado não retorna 1

            String message = "Cliente não cadastrado. Deseja cadastrar novo Cliente ?";
            String title = "Confirmação";

            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);

            if(reply == JOptionPane.YES_OPTION)
            {
                //Se escolhida a opção "Sim", abrimos a janela de cadastro "FormNovoCliente".

                FormNovoCliente form = new FormNovoCliente(null, rootPaneCheckingEnabled);
                form.setVisible(true);
            }

        }
        
    }//GEN-LAST:event_btn_pesquisaAgendamentoPesquisarActionPerformed

    private void cbo_pesquisaAgendamentoUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_pesquisaAgendamentoUnidadeActionPerformed
        
        cbo_pesquisaAgendamentoFuncionario.removeAllItems();
        
        DaoFuncionario daoFunc = new DaoFuncionario();
        
        String unidadeSelecionada = cbo_pesquisaAgendamentoUnidade.getSelectedItem().toString();
        
        ArrayList<String> lista = daoFunc.pesquisaFuncionarioPorUnidade(unidadeSelecionada);
        
        for(String s : lista){
            
            cbo_pesquisaAgendamentoFuncionario.addItem(s);
            
        }
        
    }//GEN-LAST:event_cbo_pesquisaAgendamentoUnidadeActionPerformed

    private void btn_pesquisaAgendamentoFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisaAgendamentoFiltrarActionPerformed

        
        btn_pesquisaAgendamentoPesquisarAlterar.setEnabled(true);
        
        txt_pesquisaAgendamentoId.setEnabled(true);

        String nomeFuncionario = cbo_pesquisaAgendamentoFuncionario.getSelectedItem().toString();
        
        
        DefaultTableModel model = (DefaultTableModel) tbl_pesquisaAgendamento.getModel();
            
        model.setNumRows(0);
        
        
        DaoAgendamento daoAgend = new DaoAgendamento();
        DaoClientes daoCli = new DaoClientes();
        DaoFuncionario daoFunc = new DaoFuncionario();
        
        
        Funcionario f = daoFunc.pesquisaFuncionario(nomeFuncionario);
        
        ArrayList<Agendamento> lista = daoAgend.agendamentoPorIdFuncionario(f.getIdFuncionario());
        
        
        if(lista != null){
        
            for(Agendamento a : lista){
                
                Cliente c = new Cliente();
            
                c = daoCli.pesquisaClienteId(a.getIdCliente());
            
                String nomeServico = daoFunc.pesquisaNomeServicoPorIdServico(a.getIdServico());
                                
                Date data = FormatacaoData.convertToDate(a.getDataAgendamento());
                
                model.addRow(new Object[] {a.getIdAgendamento(), 
                f.getNome(), nomeServico, FormatacaoData.convertToStringExibicao(data), a.getHoraInicio(), 
                a.getHoraFim(), a.getStatus()});
            
            }
            
        }
        
    }//GEN-LAST:event_btn_pesquisaAgendamentoFiltrarActionPerformed

    private void btn_pesquisaAgendamentoAlteraSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisaAgendamentoAlteraSituacaoActionPerformed

        cbo_pesquisaAgendamentoAlterarSituacao.setEnabled(true);

    }//GEN-LAST:event_btn_pesquisaAgendamentoAlteraSituacaoActionPerformed

    private void btn_pesquisaAgendamentoAlteraHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisaAgendamentoAlteraHoraActionPerformed

        cbo_pesquisaAgendamentoAlterarHorario.setEnabled(true);

        String data = txt_pesquisaAgendamentoData.getText();

        DaoAgendamento daoAgend = new DaoAgendamento();

        DaoFuncionario daoFunc = new DaoFuncionario();

        String nomeFuncionario = txt_pesquisaAgendamentoFuncionarioAlterar.getText();

        Funcionario f = daoFunc.pesquisaFuncionario(nomeFuncionario);

        ArrayList<String> horariosDisponiveis = daoAgend.verificaHorariosDisponiveisComSituacao(f.getIdFuncionario(), data);

        for(String s : horariosDisponiveis){

            cbo_pesquisaAgendamentoAlterarHorario.addItem(s);

        }

    }//GEN-LAST:event_btn_pesquisaAgendamentoAlteraHoraActionPerformed

    private void btn_pesquisaAgendamentoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisaAgendamentoSalvarActionPerformed

        if(btn_pesquisaAgendamentoAlteraHora.isSelected() == false &&
            btn_pesquisaAgendamentoAlteraSituacao.isSelected() == false){

            JOptionPane.showMessageDialog(rootPane, "Nenhum dado alterado");

        }
        else{

            

            String message = "Deseja alterar os dados de agendamento?";
            String title = "Confirmação";

            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);

            if(reply == JOptionPane.YES_OPTION){

                DaoAgendamento daoAgend = new DaoAgendamento();

                DaoFuncionario daoFunc = new DaoFuncionario();

                Funcionario f = daoFunc.pesquisaFuncionario(txt_pesquisaAgendamentoFuncionarioAlterar.getText());

                Agendamento a = daoAgend.agendamentoPorIdAgendamento(Integer.parseInt(txt_pesquisaAgendamentoId.getText()));

                if(btn_pesquisaAgendamentoAlteraHora.isSelected()){

                    String horarioSelecionado = cbo_pesquisaAgendamentoAlterarHorario.getSelectedItem().toString();
        
                    System.out.println(horarioSelecionado);
        
                    Horarios h = daoAgend.horaInicioHoraFim(horarioSelecionado);

                    a.setHoraInicio(h.getHoraInicio());
                    a.setHoraFim(h.getHoraFim());

                }

                if(btn_pesquisaAgendamentoAlteraSituacao.isSelected()){

                    String situacao = cbo_pesquisaAgendamentoAlterarSituacao.getSelectedItem().toString();

                    if(cbo_pesquisaAgendamentoAlterarSituacao.getSelectedItem().toString().equalsIgnoreCase("Cancelado")){

                        "Cancelado".equalsIgnoreCase(situacao);
                        a.setStatus(situacao);
                    }
                    else if(cbo_pesquisaAgendamentoAlterarSituacao.getSelectedItem().toString().equalsIgnoreCase("Atendido")){

                        "Atendido".equalsIgnoreCase(situacao);
                        a.setStatus(situacao);

                    }
                    else if(cbo_pesquisaAgendamentoAlterarSituacao.getSelectedItem().toString().equalsIgnoreCase("Em atendimento")){

                        "Em atendimento".equalsIgnoreCase(situacao);
                        a.setStatus(situacao);

                    }
                    else if(cbo_pesquisaAgendamentoAlterarSituacao.getSelectedItem().toString().equalsIgnoreCase("Fila de espera")){

                        "Fila de espera".equalsIgnoreCase(situacao);
                        a.setStatus(situacao);

                    }
                    else if(cbo_pesquisaAgendamentoAlterarSituacao.getSelectedItem().toString().equalsIgnoreCase("Agendado")){

                        "Agendado".equalsIgnoreCase(situacao);
                        a.setStatus(situacao);

                    }
                }

                daoAgend.updateAgendamento(a);

                DefaultTableModel model = (DefaultTableModel) tbl_pesquisaAgendamento.getModel();

                model.setNumRows(0);

                ArrayList<Agendamento> lista = daoAgend.agendamentoPorIdFuncionario(f.getIdFuncionario());

                if(lista != null){

                    for(Agendamento b : lista){

                        String nomeServico = daoFunc.pesquisaNomeServicoPorIdServico(b.getIdServico());

                        Date data = FormatacaoData.convertToDate(b.getDataAgendamento());
                        
                        String dataAgendamento = FormatacaoData.convertToStringExibicao(data);
                        
                        model.addRow(new Object[] {b.getIdAgendamento(),
                            f.getNome(), nomeServico, dataAgendamento, b.getHoraInicio(),
                            b.getHoraFim(), b.getStatus()});

                }
            }
        }
        }
    }//GEN-LAST:event_btn_pesquisaAgendamentoSalvarActionPerformed

    private void btn_pesquisaAgendamentoPesquisarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisaAgendamentoPesquisarAlterarActionPerformed

        cbo_pesquisaAgendamentoAlterarHorario.removeAllItems();
        
        cbo_pesquisaAgendamentoAlterarHorario.setEnabled(false);

        cbo_pesquisaAgendamentoAlterarSituacao.setEnabled(false);

        btn_pesquisaAgendamentoAlteraHora.setSelected(false);
        btn_pesquisaAgendamentoAlteraSituacao.setSelected(false);

        Integer idAgendamento = Integer.parseInt(txt_pesquisaAgendamentoId.getText());

        DaoAgendamento daoAgend = new DaoAgendamento();

        DaoFuncionario daoFunc = new DaoFuncionario();

        Agendamento a = daoAgend.agendamentoPorIdAgendamento(idAgendamento);

        if(a != null){

            btn_pesquisaAgendamentoSalvar.setEnabled(true);
            btn_pesquisaAgendamentoAlteraHora.setEnabled(true);
            btn_pesquisaAgendamentoAlteraSituacao.setEnabled(true);

            Funcionario f = daoFunc.pesquisaFuncionarioId(a.getIdFuncionario());

            txt_pesquisaAgendamentoFuncionarioAlterar.setText(f.getNome());

            txt_pesquisaAgendamentoServicoAlterar.setText(daoFunc.pesquisaNomeServicoPorIdServico(a.getIdServico()));

            txt_pesquisaAgendamentoData.setText(a.getDataAgendamento());

            txt_pesquisaAgendamentoHorarioInicio.setText(a.getHoraInicio());

            txt_pesquisaAgendamentoHorarioFim.setText(a.getHoraFim());

            txt_pesquisaAgendamentoSituacao.setText(a.getStatus());

        }
        else{

            JOptionPane.showMessageDialog(rootPane, "Agendamento não encontrado.");

        }

    }//GEN-LAST:event_btn_pesquisaAgendamentoPesquisarAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPesquisaAgendamento dialog = new FormPesquisaAgendamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btn_pesquisaAgendamentoAlteraHora;
    private javax.swing.JCheckBox btn_pesquisaAgendamentoAlteraSituacao;
    private javax.swing.JButton btn_pesquisaAgendamentoFiltrar;
    private javax.swing.JButton btn_pesquisaAgendamentoPesquisar;
    private javax.swing.JButton btn_pesquisaAgendamentoPesquisarAlterar;
    private javax.swing.JButton btn_pesquisaAgendamentoSalvar;
    private javax.swing.JComboBox cbo_pesquisaAgendamentoAlterarHorario;
    private javax.swing.JComboBox cbo_pesquisaAgendamentoAlterarSituacao;
    private javax.swing.JComboBox cbo_pesquisaAgendamentoFuncionario;
    private javax.swing.JComboBox cbo_pesquisaAgendamentoUnidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoRakusPeqNCli;
    private javax.swing.JTable tbl_pesquisaAgendamento;
    private javax.swing.JTextField txt_pesquisaAgendamentoCliente;
    private javax.swing.JFormattedTextField txt_pesquisaAgendamentoCpf;
    private javax.swing.JTextField txt_pesquisaAgendamentoData;
    private javax.swing.JTextField txt_pesquisaAgendamentoFuncionarioAlterar;
    private javax.swing.JLabel txt_pesquisaAgendamentoHorario;
    private javax.swing.JTextField txt_pesquisaAgendamentoHorarioFim;
    private javax.swing.JTextField txt_pesquisaAgendamentoHorarioInicio;
    private javax.swing.JTextField txt_pesquisaAgendamentoId;
    private javax.swing.JTextField txt_pesquisaAgendamentoServicoAlterar;
    private javax.swing.JTextField txt_pesquisaAgendamentoSituacao;
    // End of variables declaration//GEN-END:variables
}
