
package visual;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import piagendamentos.Cliente;
import piagendamentos.DaoClientes;


public class FormPesquisaCliente extends javax.swing.JDialog {

    
    //Criando a tabela
            
    
    
    


    
    
    public static boolean alteracao;
    public static boolean clienteSelecionado;
    
    
    /**
     * Creates new form FormNovoCliente
     */
    public FormPesquisaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_PesqCpf = new javax.swing.JTextField();
        btn_PesquisarCliente = new javax.swing.JButton();
        btn_PesqLimpar = new javax.swing.JButton();
        btn_PesqCadastrar = new javax.swing.JButton();
        btn_PesqFechar = new javax.swing.JButton();
        logoRakusPeqNCli = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabelaPesquisaClientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_PesquisaCliTelFixo = new javax.swing.JTextField();
        txt_PesquisaCliSexo = new javax.swing.JTextField();
        txt_PesquisaCliNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_PesqAlterar = new javax.swing.JButton();
        btn_PesqSalvar = new javax.swing.JButton();
        btn_PesqAtualizarTabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rankuspelus - Pesquisa de Cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 18))); // NOI18N

        jLabel2.setText("CPF");

        btn_PesquisarCliente.setText("Pesquisar");
        btn_PesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarClienteActionPerformed(evt);
            }
        });

        btn_PesqLimpar.setText("Limpar");
        btn_PesqLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesqLimparActionPerformed(evt);
            }
        });

        btn_PesqCadastrar.setText("Cadastrar");
        btn_PesqCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesqCadastrarActionPerformed(evt);
            }
        });

        btn_PesqFechar.setText("Fechar");
        btn_PesqFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesqFecharActionPerformed(evt);
            }
        });

        logoRakusPeqNCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoRankupeluspequeno.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_PesqCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_PesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_PesqLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_PesqCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_PesqFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoRakusPeqNCli)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoRakusPeqNCli)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_PesqCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_PesquisarCliente)
                            .addComponent(btn_PesqLimpar)
                            .addComponent(btn_PesqCadastrar)
                            .addComponent(btn_PesqFechar))))
                .addGap(38, 38, 38))
        );

        tbl_tabelaPesquisaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Sexo", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_tabelaPesquisaClientes);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 18))); // NOI18N

        jLabel5.setText("Telefone");

        txt_PesquisaCliTelFixo.setEditable(false);

        txt_PesquisaCliSexo.setEditable(false);

        txt_PesquisaCliNome.setEditable(false);

        jLabel1.setText("Nome");

        jLabel4.setText("Sexo");

        btn_PesqAlterar.setText("Alterar Dados");
        btn_PesqAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesqAlterarActionPerformed(evt);
            }
        });

        btn_PesqSalvar.setText("Salvar");
        btn_PesqSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesqSalvarActionPerformed(evt);
            }
        });

        btn_PesqAtualizarTabela.setText("Atualizar Tabela");
        btn_PesqAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesqAtualizarTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_PesquisaCliNome, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_PesquisaCliSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_PesquisaCliTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_PesqSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_PesqAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_PesqAtualizarTabela))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_PesqAlterar)
                        .addGap(8, 8, 8)
                        .addComponent(btn_PesqSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(btn_PesqAtualizarTabela))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_PesquisaCliNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_PesquisaCliSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_PesquisaCliTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btn_PesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarClienteActionPerformed

        
            
            clienteSelecionado = false;
            
            DaoClientes daoClientes = new DaoClientes();
            
            if(daoClientes.verificaExistencia(txt_PesqCpf.getText().replaceAll("[./-]", ""))){
            
            clienteSelecionado = true;
                
            Cliente cliente = daoClientes.pesquisaCliente(txt_PesqCpf.getText().replaceAll("[./-]", ""));
            
            txt_PesquisaCliNome.setText(cliente.getNome());
            txt_PesquisaCliSexo.setText(cliente.getSexo());
            txt_PesquisaCliTelFixo.setText(cliente.getTelFixo());
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Cliente não cadastrado");
                
                txt_PesqCpf.setText("");
                txt_PesquisaCliNome.setText("");
                txt_PesquisaCliSexo.setText("");
                txt_PesquisaCliTelFixo.setText("");
            }
            
            
            //Criando a tabela
            
            DefaultTableModel model = (DefaultTableModel) tbl_tabelaPesquisaClientes.getModel();
            
            model.setNumRows(0);
            
            Cliente clienteTabela = daoClientes.pesquisaCliente(txt_PesqCpf.getText());
            
            

            try {
            
                DaoClientes dao = new DaoClientes();
            
                ArrayList<Cliente> lista = new ArrayList<Cliente>();
            
                lista = dao.findAll();
            
                if(lista != null){
                
                    for(Cliente c : lista){
                
                        model.addRow(new Object[] {c.getNome(), 
                        c.getCpf(), c.getSexo(), c.getTelFixo()});
                
                    }
                }


            } catch (Exception e) {
                System.out.println("Erro: " + e.getMessage());
            }

            
            


    }//GEN-LAST:event_btn_PesquisarClienteActionPerformed

    private void btn_PesqLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesqLimparActionPerformed
        
        txt_PesqCpf.setText("");
        txt_PesquisaCliNome.setText("");
        txt_PesquisaCliSexo.setText("");
        txt_PesquisaCliTelFixo.setText("");
        
    }//GEN-LAST:event_btn_PesqLimparActionPerformed

    private void btn_PesqCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesqCadastrarActionPerformed
        
        
        FormNovoCliente form = new FormNovoCliente(null, rootPaneCheckingEnabled);
        form.setVisible(true);
        
    }//GEN-LAST:event_btn_PesqCadastrarActionPerformed

    private void btn_PesqFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesqFecharActionPerformed
        
        FormPesquisaCliente.this.dispose();
        
    }//GEN-LAST:event_btn_PesqFecharActionPerformed

    private void btn_PesqAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesqAlterarActionPerformed

        
        if(txt_PesquisaCliNome.getText().equals("")){
            
            JOptionPane.showMessageDialog(rootPane, "Nenhum cliente selecionado");
            
        }
        
        else if(clienteSelecionado){
        
        String message = "Alterar dados do cliente ?";
        String title = "Confirmação";
        
        //Exibe caixa de dialogo solicitando confirmação ou não. 
        //Se o usuário clicar em "Sim" retorna 0 pra variavel reply, se informado não retorna 1
        
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            alteracao = true;
            
            txt_PesquisaCliNome.setEditable(true);
            txt_PesquisaCliSexo.setEditable(true);
            txt_PesquisaCliTelFixo.setEditable(true);
        }
        }
        
        
    }//GEN-LAST:event_btn_PesqAlterarActionPerformed

    private void btn_PesqSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesqSalvarActionPerformed
        
        
        if(txt_PesqCpf.getText().equals("")){
            
            JOptionPane.showMessageDialog(rootPane, "Nenhum cliente selecionado");
            
        }
        else if (alteracao == false){
            
            JOptionPane.showMessageDialog(rootPane, "Nenhum dado foi alterado");  
        }
        else if (alteracao){
            
            DaoClientes daoCliente = new DaoClientes();
            
            daoCliente.alteraCliente(txt_PesqCpf.getText(), txt_PesquisaCliNome.getText(), 
                    txt_PesquisaCliSexo.getText(), txt_PesquisaCliTelFixo.getText());
            
            JOptionPane.showMessageDialog(rootPane, "Dados alterados com sucesso");
            
            txt_PesquisaCliNome.setEditable(false);
            txt_PesquisaCliSexo.setEditable(false);
            txt_PesquisaCliTelFixo.setEditable(false);
            
        }
        
    }//GEN-LAST:event_btn_PesqSalvarActionPerformed

    private void btn_PesqAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesqAtualizarTabelaActionPerformed
        
        
        //Criando a tabela
            
        DefaultTableModel model = (DefaultTableModel) tbl_tabelaPesquisaClientes.getModel();
            
        model.setNumRows(0);
                       

        try {
            
            DaoClientes dao = new DaoClientes();
            
            ArrayList<Cliente> lista = new ArrayList<Cliente>();
            
            lista = dao.findAll();
            
            if(lista != null){
                
                for(Cliente c : lista){
                
                    model.addRow(new Object[] {c.getNome(), 
                    c.getCpf(), c.getSexo(), c.getTelFixo()});
                
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(FormPesquisaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_PesqAtualizarTabelaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        DaoClientes daoCli = new DaoClientes();
        
        daoCli.preencheTabela(tbl_tabelaPesquisaClientes);
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPesquisaCliente dialog = new FormPesquisaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_PesqAlterar;
    private javax.swing.JButton btn_PesqAtualizarTabela;
    private javax.swing.JButton btn_PesqCadastrar;
    private javax.swing.JButton btn_PesqFechar;
    private javax.swing.JButton btn_PesqLimpar;
    private javax.swing.JButton btn_PesqSalvar;
    private javax.swing.JButton btn_PesquisarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoRakusPeqNCli;
    private javax.swing.JTable tbl_tabelaPesquisaClientes;
    private javax.swing.JTextField txt_PesqCpf;
    private javax.swing.JTextField txt_PesquisaCliNome;
    private javax.swing.JTextField txt_PesquisaCliSexo;
    private javax.swing.JTextField txt_PesquisaCliTelFixo;
    // End of variables declaration//GEN-END:variables
}
