/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import piagendamentos.Agendamento;
import piagendamentos.DaoAgendamento;
import piagendamentos.DaoFuncionario;
import piagendamentos.Funcionario;
import piagendamentos.util.FormatacaoData;

/**
 *
 * @author Elder
 */
public class FormFuncionariosEmAtendimento extends javax.swing.JDialog {

    /**
     * Creates new form FormNovoCliente
     */
    public FormFuncionariosEmAtendimento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoRakusPeqNCli = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbo_FuncionariosEmAtendimentoUnidades = new javax.swing.JComboBox();
        btn_FuncionariosEmAtendimentoBuscar = new javax.swing.JButton();
        cbo_FuncionariosEmAtendimentoGerarRelatorio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pesquisaFuncionariosEmAtendimento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rankuspelus - Relatório por Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        logoRakusPeqNCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoRankupeluspequeno.gif"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funcionários em Atendimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 18))); // NOI18N

        jLabel2.setText("Unidade:");

        btn_FuncionariosEmAtendimentoBuscar.setText("Buscar");
        btn_FuncionariosEmAtendimentoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FuncionariosEmAtendimentoBuscarActionPerformed(evt);
            }
        });

        cbo_FuncionariosEmAtendimentoGerarRelatorio.setText("Gerar Relatório");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(cbo_FuncionariosEmAtendimentoUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_FuncionariosEmAtendimentoBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbo_FuncionariosEmAtendimentoGerarRelatorio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbo_FuncionariosEmAtendimentoUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_FuncionariosEmAtendimentoBuscar)
                    .addComponent(cbo_FuncionariosEmAtendimentoGerarRelatorio))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tbl_pesquisaFuncionariosEmAtendimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Agendamento", "Funcionário", "Serviço", "Data", "Horário Início", "Horário Fim", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_pesquisaFuncionariosEmAtendimento.setFillsViewportHeight(true);
        tbl_pesquisaFuncionariosEmAtendimento.setFocusable(false);
        tbl_pesquisaFuncionariosEmAtendimento.setInheritsPopupMenu(true);
        tbl_pesquisaFuncionariosEmAtendimento.setRequestFocusEnabled(false);
        tbl_pesquisaFuncionariosEmAtendimento.setRowSelectionAllowed(false);
        tbl_pesquisaFuncionariosEmAtendimento.setUpdateSelectionOnSort(false);
        tbl_pesquisaFuncionariosEmAtendimento.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(tbl_pesquisaFuncionariosEmAtendimento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoRakusPeqNCli))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(logoRakusPeqNCli))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        cbo_FuncionariosEmAtendimentoUnidades.removeAllItems();
        
        DaoAgendamento daoAgend = new DaoAgendamento();
        
        ArrayList<String> lista = new ArrayList();
        
        lista = daoAgend.pesquisaUnidades();

        for(String s : lista){
                
            cbo_FuncionariosEmAtendimentoUnidades.addItem(s);
                
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btn_FuncionariosEmAtendimentoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FuncionariosEmAtendimentoBuscarActionPerformed
        
        DaoAgendamento daoAg = new DaoAgendamento();
        
        DaoFuncionario daoFunc = new DaoFuncionario();
        
        String dataAtual = FormatacaoData.getDateTime();
        
        String nomeUnidade = cbo_FuncionariosEmAtendimentoUnidades.getSelectedItem().toString();
        
        String status = "Em atendimento";
        
        Integer idUnidade = daoAg.pesquisaUnidadePorNomeUnidade(nomeUnidade);
        
        ArrayList<Agendamento> lista = daoAg.pesquisaAgendamentosEmExecucaoPorUnidade(status, idUnidade, dataAtual);
        
        DefaultTableModel model = (DefaultTableModel) tbl_pesquisaFuncionariosEmAtendimento.getModel();

            model.setNumRows(0);

            if(lista != null){

                for(Agendamento a : lista){
                    
                    Funcionario f = daoFunc.pesquisaFuncionarioId(a.getIdFuncionario());

                    String nomeServico = daoFunc.pesquisaNomeServicoPorIdServico(a.getIdServico());

                    Date data = FormatacaoData.convertToDate(a.getDataAgendamento());
                        
                    String dataAgendamento = FormatacaoData.convertToString(data);
                        
                    model.addRow(new Object[] {a.getIdAgendamento(),
                        f.getNome(), nomeServico, dataAgendamento, a.getHoraInicio(),
                        a.getHoraFim(), a.getStatus()});

                }
            }
            else{
                
                System.out.println("");
                
            }
        
    }//GEN-LAST:event_btn_FuncionariosEmAtendimentoBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionariosEmAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionariosEmAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionariosEmAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionariosEmAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormFuncionariosEmAtendimento dialog = new FormFuncionariosEmAtendimento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_FuncionariosEmAtendimentoBuscar;
    private javax.swing.JButton cbo_FuncionariosEmAtendimentoGerarRelatorio;
    private javax.swing.JComboBox cbo_FuncionariosEmAtendimentoUnidades;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoRakusPeqNCli;
    private javax.swing.JTable tbl_pesquisaFuncionariosEmAtendimento;
    // End of variables declaration//GEN-END:variables
}
